const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { spawn } = require('node:child_process');
const sqlite3 = require('sqlite3');
const net = require('node:net');
const { once } = require('node:events');
const root = path.join(__dirname, '..');
const run = (db, sql, args=[]) => new Promise((resolve,reject)=>db.run(sql,args,e=>e?reject(e):resolve()));

test('real server serves canonical, sitemap, noindex, admin guard and SSR links consistently', {timeout:30000}, async t => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'xput-seo-'));
  t.after(() => fs.rmSync(dir, {recursive:true,force:true}));
  const listener = net.createServer(); listener.listen(0,'127.0.0.1'); await once(listener,'listening');
  const port = listener.address().port; await new Promise(r=>listener.close(r));
  const env = {...process.env, PORT:String(port), DATA_DIR:dir, ARCHIVES_DIR:path.join(dir,'archives'), SQLITE_PATH:path.join(dir,'db.sqlite'), PUBLIC_BASE_URL:'https://xput.app', MODERATION_ADMIN_TOKEN:'test-only-token', SEO_AUTO_INDEX:'true'};
  const child = spawn(process.execPath, ['server.js'], {cwd:root, env, stdio:['ignore','pipe','pipe']});
  t.after(async()=>{ if(child.exitCode===null){ child.kill(); await once(child,'exit'); } });
  let output=''; child.stdout.on('data',b=>output+=b);child.stderr.on('data',b=>output+=b);
  const base = `http://127.0.0.1:${port}`;
  for(let i=0;i<100;i++){
    try { if((await fetch(base+'/healthz')).ok) break; } catch {}
    if(child.exitCode!==null) throw new Error(output);
    await new Promise(r=>setTimeout(r,50));
  }
  const db = new sqlite3.Database(env.SQLITE_PATH);
  t.after(()=>new Promise(r=>db.close(r)));
  fs.mkdirSync(path.join(dir,'images'),{recursive:true});fs.writeFileSync(path.join(dir,'images','sample.jpg'),'test');
  const content = '<p>'+Array.from({length:170},(_,i)=>`word${i}`).join(' ')+'</p>';
  await run(db, 'INSERT INTO posts(id,url,short_code,content,images,author,author_handle,tweet_time,html_file) VALUES(?,?,?,?,?,?,?,?,?)', [1,'https://x.com/i/status/123','Ab1234',content,'["/images/sample.jpg"]','Alice','alice','2026-09-26T01:00:00Z','post_123.html']);
  let page = await (await fetch(base+'/Ab1234')).text();
  assert.match(page, /content="noindex, follow"/);
  assert.match(page, /property="og:image" content="https:\/\/xput.app\/images\/sample.jpg"/);
  assert.match(page, /<html lang="en">/);
  await run(db, "UPDATE posts SET images='[]' WHERE id=1");
  const fallbackPage = await (await fetch(base+'/Ab1234')).text();
  for (const tag of ['property="og:image"', 'name="twitter:image"']) {
    assert.ok(fallbackPage.includes(`<meta ${tag} content="https://xput.app/xput-share.png">`));
  }
  const shareImage = await fetch(base+'/xput-share.png');
  assert.equal(shareImage.status, 200);
  assert.match(shareImage.headers.get('content-type'), /image\/png/);
  await run(db, 'UPDATE posts SET images=? WHERE id=1', ['["/images/sample.jpg"]']);
  assert.match(await (await fetch(base+'/')).text(), /href="\/Ab1234"/);
  assert.equal((await fetch(base+'/api/admin/seo')).status,403);
  const action=async body=>fetch(base+'/api/admin/seo/1',{method:'POST',headers:{'Content-Type':'application/json','x-admin-token':'test-only-token'},body:JSON.stringify(body)});
  assert.equal((await action({override:'index',blocked:'false'})).status,400);
  assert.equal((await (await action({override:null,blocked:false})).json()).status,'index');
  page = await (await fetch(base+'/Ab1234')).text();assert.match(page,/content="index, follow"/);
  assert.match(await (await fetch(base+'/sitemap.xml')).text(), /\/Ab1234/);
  assert.match(await (await fetch(base+'/browse')).text(), /\/Ab1234/);
  await run(db, 'INSERT INTO posts(id,url,short_code,content,images,author,author_handle,tweet_time,html_file,seo_status,seo_blocked) VALUES(?,?,?,?,?,?,?,?,?,?,?)', [2,'https://x.com/i/status/456','Cd3456','<h1>Needle guide</h1><p>Searchable archive</p>','[]','Bob Builder','bob_builder','2026-09-26T02:00:00Z','post_456.html','index',0]);
  const searchPage = await (await fetch(base+'/browse?q=needle')).text();
  assert.match(searchPage, /href="\/Cd3456"/);
  assert.doesNotMatch(searchPage, /href="\/Ab1234"/);
  assert.match(searchPage, /value="needle"/);
  assert.match(searchPage, /content="noindex, follow"/);
  const authorSearch = await (await fetch(base+'/browse?q=bob_builder')).text();
  assert.match(authorSearch, /href="\/Cd3456"/);
  const get=(sql,args=[])=>new Promise((resolve,reject)=>db.get(sql,args,(e,row)=>e?reject(e):resolve(row)));
  const generatedPost=await get('SELECT * FROM posts WHERE id=2');
  const generatedHash=require('../lib/seo-title').fingerprint(generatedPost);
  await run(db,'UPDATE posts SET seo_title=?,seo_description=?,seo_title_hash=? WHERE id=2',['Needle archive guide','An archived guide.',generatedHash]);
  for(const route of ['/Cd3456','/browse','/']) {
    const html=await(await fetch(base+route)).text();assert.match(html,/Needle archive guide/);
    if(route==='/Cd3456')assert.equal((html.match(/<h1\b/g)||[]).length,1);
  }
  const apiPosts=await(await fetch(base+'/api/posts')).json();
  assert.equal(apiPosts.posts.find(p=>p.id===2).title,'Needle archive guide');
  const escapedSearch = await (await fetch(base+'/browse?q=%3Cscript%3E')).text();
  assert.match(escapedSearch, /value="&lt;script&gt;"/);
  assert.doesNotMatch(escapedSearch, /value="<script>"/);
  const legacy=await fetch(base+'/archives/post_123.html',{redirect:'manual'});
  assert.equal(legacy.status,301);assert.equal(legacy.headers.get('location'),'/Ab1234');
  await run(db,'INSERT INTO post_aliases(alias_code,target_post_id) VALUES(?,?)',['Cd5678',1]);
  assert.equal((await fetch(base+'/Cd5678',{redirect:'manual'})).status,301);
  for(const p of ['/demo/','/admin-xput.html','/api/posts']) assert.match((await fetch(base+p)).headers.get('x-robots-tag'),/noindex/);
  const robots=await(await fetch(base+'/robots.txt')).text();assert.match(robots,/Sitemap: https:\/\/xput.app\/sitemap.xml/);assert.match(robots,/Disallow: \/api\/archive\//);assert.doesNotMatch(robots,/Disallow: \/(?:demo|admin)/);
  await action({override:'index',blocked:true});
  assert.equal((await (await action({override:'index'})).json()).status,'noindex', 'recommend does not clear a block');
  assert.doesNotMatch(await(await fetch(base+'/sitemap.xml')).text(),/Ab1234/);
  assert.match(await(await fetch(base+'/Ab1234')).text(),/noindex/);
  const reportResponse = await fetch(base+'/api/reports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:'https://xput.app/Ab1234',kind:'privacy',reason:'Please remove my private personal information.',contact:'person@example.com'})});
  assert.equal(reportResponse.status,201);
  const reportId=(await reportResponse.json()).id;
  assert.equal((await fetch(base+'/api/admin/reports')).status,403);
  const reportList=await (await fetch(base+'/api/admin/reports',{headers:{'x-admin-token':'test-only-token'}})).json();
  assert.equal(reportList.reports[0].id,reportId);
  const closed=await fetch(base+'/api/admin/reports/'+reportId,{method:'POST',headers:{'Content-Type':'application/json','x-admin-token':'test-only-token'},body:JSON.stringify({action:'block'})});
  assert.equal(closed.status,200);
  assert.equal((await fetch(base+'/report')).status,200);
  const home=await (await fetch(base+'/')).text();
  assert.match(home,/href="\/help"/);assert.match(home,/og:image/);assert.match(home,/href="\/report"/);
  assert.match(await (await fetch(base+'/Ab1234')).text(),/SocialMediaPosting/);
  assert.match((await fetch(base+'/Ab1234/referer',{redirect:'manual'})).headers.get('x-robots-tag'),/noindex/);
  await run(db,'DELETE FROM posts WHERE id IN (1,2)');
  fs.writeFileSync(path.join(dir,'archives','post_123.html'),'stale indexable html');
  assert.equal((await fetch(base+'/Ab1234')).status,404);
  assert.equal((await fetch(base+'/archives/post_123.html')).status,404);
});
